services:
  db:
    image: postgres:14
    restart: always
    env_file:
      - .env.prod
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_v14:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    restart: always
    # Port 3000 tidak lagi diekspos ke host, hanya bisa diakses dari dalam jaringan docker
    env_file:
      - .env.prod
    depends_on:
      db:
        condition: service_healthy

  # BARU: Service untuk Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80" # Ekspos port 80 ke host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Mount file konfigurasi (read-only)
    depends_on:
      - backend

volumes:
  postgres_data_v14:
